apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.21.6
        ports:
          - containerPort: 80
        resources: {}


---


apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: init-myservice
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -vz nginx 80 2>&1; do echo "Waiting for nginx service" ; sleep 2; done;']
        resources: {}
    