apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: app
spec:
  selector:
    app: nginx
  type: LoadBalancer
  loadBalancerIP: 10.0.0.5
  ports:
  - name: nginx
    protocol: TCP
    port: 80
    targetPort: 80