apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: app
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node
            values:
            - worker2
            operator: In
  containers:
  - name: nginx-container
    image: nginx:1.21.6
    ports:
        - containerPort: 80
    resources: {}
#kubectl label nodes worker2 node=worker2
