apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: app
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Welcome to My Website</title>
    </head>
    <body>
        <h1>Hello, this is my website!</h1>
    </body>
    </html>

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: app
spec:
  containers:
  - name: nginx-container
    image: nginx:1.21.6
    ports:
        - containerPort: 80
    volumeMounts:
    - name: nginx-config-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nginx-config-volume
    configMap:
      name: nginx-config
  
