apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: app
spec:
  tolerations:
  - key: "node"
    value: "worker2"
    operator: "Equal"
    effect: "NoSchedule"
  containers:
  - name: nginx-container
    image: nginx:1.21.6
    ports:
        - containerPort: 80
  
#kubectl taint nodes worker2 node=worker2:NoSchedule
