apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: app
spec:
  containers:
  - name: nginx-container
    image: nginx:1.21.6
    ports:
        - containerPort: 80


---

apiVersion: v1
kind: Pod
metadata:
  name: prometheus-pod
  namespace: monitoring
spec:
  containers:
  - name: prometheus-container
    image: prom/prometheus:v2.47.1
    ports:
        - containerPort: 9090